### ISSUE TITLE
need more pics of cats

### ISSUE THREAD

**Issue by stephenplusplus** [taptapship/sindresorhus#1]

**Comment by sindresorhus** [comment]
![superhighfive](https://f.cloud.github.com/assets/170270/2091180/f85d4f6c-8e9d-11e3-841a-b1feb8530ce5.gif)
![hy0olss](https://f.cloud.github.com/assets/170270/2091181/f85e9cf0-8e9d-11e3-9c08-a27c0fcdb244.gif)
![tumblr_mzh8k0zeds1qdlh1io1_250](https://f.cloud.github.com/assets/170270/2091182/f87295ac-8e9d-11e3-9f37-7f1aec596faf.gif)
![tumblr_mzqocmy8ct1qdlh1io1_400-1](https://f.cloud.github.com/assets/170270/2091183/f87417e2-8e9d-11e3-81d7-f6018215f360.gif)
![ponycarrots](https://f.cloud.github.com/assets/170270/2091184/f8877bc0-8e9d-11e3-825b-cf7a31bb7bea.gif)
![celebritycarrots](https://f.cloud.github.com/assets/170270/2091186/f887c0da-8e9d-11e3-9f2b-b44480ded1bf.gif)
![catstarwars](https://f.cloud.github.com/assets/170270/2091185/f887bbee-8e9d-11e3-8167-6854514df963.gif)
![tumblr_mjedslipph1qbyxr0o1_500](https://f.cloud.github.com/assets/170270/2091187/f888e618-8e9d-11e3-8ba3-0ff415330f52.gif)
![732852c4-67d8-11e3-90c3-576016e1aac4](https://f.cloud.github.com/assets/170270/2091188/f88a1916-8e9d-11e3-9568-60b77a5cd400.gif)
![tumblr_mwmm7cftgi1s373hwo1_250](https://f.cloud.github.com/assets/170270/2091189/f88a77b2-8e9d-11e3-8689-f818d9bea407.gif)
![highfive2](https://f.cloud.github.com/assets/170270/2091190/f89c55f4-8e9d-11e3-9fe4-da5fd262f031.gif)
![ilovemyonlinefriends](https://f.cloud.github.com/assets/170270/2091191/f89c8484-8e9d-11e3-8a79-0d446078f99f.gif)
![cat_lick](https://f.cloud.github.com/assets/170270/2091192/f89d0aa8-8e9d-11e3-88a3-626f2b0dcfc1.gif)
![ross](https://f.cloud.github.com/assets/170270/2091193/f89dd87a-8e9d-11e3-92dd-7c2e4a7a4038.gif)
![tumblr_mv5lmwja871qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091194/f89ee8be-8e9d-11e3-8084-0890aef2c885.gif)
![tumblr_muzz73bxwu1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091195/f89fb474-8e9d-11e3-8e19-94e20bf4b793.gif)
![dcd5fce8-1c7f-11e3-9b7e-a4a0d2fda2c3](https://f.cloud.github.com/assets/170270/2091196/f8b0e424-8e9d-11e3-875a-db8a3a9c0a58.gif)
![tumblr_lrv6o0rpua1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091197/f8b0e0dc-8e9d-11e3-887c-3b63c7c0dc43.gif)
![tumblr_lqcc3hiaas1r24ezoo1_500](https://f.cloud.github.com/assets/170270/2091198/f8b213d0-8e9d-11e3-91f1-4fa73960b9c1.gif)
![tumblr_lw0usxqckd1qdlh1io1_250](https://f.cloud.github.com/assets/170270/2091199/f8b30f38-8e9d-11e3-9f67-1d511cb2ec69.gif)
![conan-hulk](https://f.cloud.github.com/assets/170270/2091201/f8b4e1e6-8e9d-11e3-851d-e0cc5b010c53.gif)
![tumblr_lxmgx9wfza1qdlh1io1_r1_400](https://f.cloud.github.com/assets/170270/2091200/f8b48548-8e9d-11e3-9991-e1d9eafaa1c3.gif)
![tumblr_lxtkhpiizk1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091202/f8c4ad38-8e9d-11e3-9150-ac240689a480.gif)
![angry-panda](https://f.cloud.github.com/assets/170270/2091203/f8c58622-8e9d-11e3-9946-74a00461a462.gif)
![tumblr_lxx3edkjhr1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091204/f8c668c6-8e9d-11e3-9caf-76aec6a8c2cf.gif)
![giphy](https://f.cloud.github.com/assets/170270/2091205/f8c86112-8e9d-11e3-8ba7-24203bf9fbfc.gif)
![c9x6n](https://f.cloud.github.com/assets/170270/2091206/f8c9e474-8e9d-11e3-94ad-f3d8757cb5ca.gif)
![xaxav](https://f.cloud.github.com/assets/170270/2091207/f8ca4d4c-8e9d-11e3-8cac-e5b8b9d46eb8.gif)
![r6qrd](https://f.cloud.github.com/assets/170270/2091208/f8d8b38c-8e9d-11e3-9a22-4bcc13abcf6a.gif)
![umpoi](https://f.cloud.github.com/assets/170270/2091209/f8da5e1c-8e9d-11e3-8ccc-0a76318d58e8.gif)
![tumblr_msmvu2aenp1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091210/f8db2cc0-8e9d-11e3-873f-2355ac89eed6.gif)
![tumblr_lyn1952vpc1qdlh1io1_r2_400](https://f.cloud.github.com/assets/170270/2091211/f8de08dc-8e9d-11e3-828e-dc1855e11d45.gif)
![tumblr_lzgr8pqy7r1qdlh1io1_250](https://f.cloud.github.com/assets/170270/2091212/f8defc1a-8e9d-11e3-81f9-e2404f6667c5.gif)
![teamwork](https://f.cloud.github.com/assets/170270/2091213/f8dfa17e-8e9d-11e3-9288-6b1544b18908.gif)
![tumblr_m1dcn3bytx1qdlh1io1_r1_250](https://f.cloud.github.com/assets/170270/2091214/f8ed7664-8e9d-11e3-8f98-d7654c24308b.gif)
![tumblr_m3twrolwpn1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091215/f8eef9b2-8e9d-11e3-9bcb-7a59f1bf718c.gif)
![tumblr_m4rz1h2lw21qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091216/f8f10310-8e9d-11e3-8e69-0962937f5546.gif)
![tumblr_m4vps8juqp1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091217/f8f326cc-8e9d-11e3-8e90-772c9eef6140.gif)
![tumblr_m50m0bylr21qdlh1io1_r1_400](https://f.cloud.github.com/assets/170270/2091218/f8f3f386-8e9d-11e3-8377-2ce90b963d8c.gif)
![tumblr_m5nhx2oe3g1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091219/f8f4c2ca-8e9d-11e3-9921-f68d07b631a5.gif)
![tumblr_m6hadxla1u1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091220/f901c4c0-8e9d-11e3-99b2-4bcba939f634.gif)
![tumblr_m7t9y9iwjv1qdlh1io1_250](https://f.cloud.github.com/assets/170270/2091221/f9028dba-8e9d-11e3-99a5-dd389f761178.gif)
![tumblr_makulzqkov1qdlh1io1_r1_400](https://f.cloud.github.com/assets/170270/2091222/f9061750-8e9d-11e3-851e-6d0445ff7b91.gif)
![tumblr_mbltcmxcgh1qdlh1io1_r1_500](https://f.cloud.github.com/assets/170270/2091223/f907e5bc-8e9d-11e3-94d9-dda713cf0ae1.gif)
![tumblr_md8q4sc9ok1qdlh1io1_r1_400](https://f.cloud.github.com/assets/170270/2091224/f908c022-8e9d-11e3-9f04-d93f9c9afe64.gif)
![dt2nrpq](https://f.cloud.github.com/assets/170270/2091225/f909d9c6-8e9d-11e3-9083-2f2d8c04a692.gif)
![tumblr_ms960vdlii1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091226/f915fe90-8e9d-11e3-8d15-715bb7ee720d.gif)
![programming](https://f.cloud.github.com/assets/170270/2091227/f916d914-8e9d-11e3-89c5-a415bf3057bc.gif)
![noqsmqe](https://f.cloud.github.com/assets/170270/2091228/f91b8540-8e9d-11e3-848e-201bd49088f8.gif)
![highfive](https://f.cloud.github.com/assets/170270/2091229/f91cc392-8e9d-11e3-806a-b6fb64188123.gif)
![x42pwrt](https://f.cloud.github.com/assets/170270/2091230/f91db248-8e9d-11e3-83d3-7604802b43d3.gif)
![qjvjabt](https://f.cloud.github.com/assets/170270/2091231/f91f9cca-8e9d-11e3-9e3b-8a1dcab8e165.gif)
![ejh8iyn](https://f.cloud.github.com/assets/170270/2091233/f92a9c6a-8e9d-11e3-9294-33a54442fc68.gif)
![f99qsln](https://f.cloud.github.com/assets/170270/2091232/f92a85ea-8e9d-11e3-9aa1-c6c43f589efe.gif)
![717sfhl](https://f.cloud.github.com/assets/170270/2091234/f9312d28-8e9d-11e3-8c4a-6d5acb52ed15.gif)
![onp4zqb](https://f.cloud.github.com/assets/170270/2091236/f9322d0e-8e9d-11e3-94e2-613222dc6b27.gif)
![2mrww5j](https://f.cloud.github.com/assets/170270/2091235/f9320112-8e9d-11e3-8d08-0ec5216093b3.gif)
![qmo3iii](https://f.cloud.github.com/assets/170270/2091237/f93548e0-8e9d-11e3-93ee-0afd48995d26.gif)
![ztpkhai](https://f.cloud.github.com/assets/170270/2091239/f93fadc6-8e9d-11e3-9562-c3fff854dacc.gif)
![tumblr_ms2ti6kedp1qdlh1io1_r2_400](https://f.cloud.github.com/assets/170270/2091238/f93f83fa-8e9d-11e3-9bdb-93b323eedd99.gif)
![tumblr_mrwspmlpfy1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091240/f946dc2c-8e9d-11e3-8ea5-95e086382324.gif)
![tumblr_mfxt0yc2cs1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091241/f9479086-8e9d-11e3-8b15-96a7c735e99a.gif)
![ibubeciygbderf](https://f.cloud.github.com/assets/170270/2091242/f9480e08-8e9d-11e3-875b-7b93c9bdf063.gif)
![tumblr_mg2r71jozx1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091243/f94c7d58-8e9d-11e3-8a48-d9fd9cc67736.gif)
![tumblr_mhezh4g36r1qdlh1io1_250](https://f.cloud.github.com/assets/170270/2091244/f9556058-8e9d-11e3-80bf-c3695393fece.gif)
![tumblr_mgi55bqnrp1qdlh1io1_500](https://f.cloud.github.com/assets/170270/2091245/f95572fa-8e9d-11e3-81a5-b71317f0d49d.gif)
![tumblr_mhj2yfholm1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091246/f95c6a74-8e9d-11e3-81b3-e90407aaede4.gif)
![tumblr_lx1w5eh9kk1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091247/f95d414c-8e9d-11e3-80dd-2696bb567dc7.gif)
![tumblr_mi8uqtsmlu1qdlh1io1_500](https://f.cloud.github.com/assets/170270/2091248/f95d9a2a-8e9d-11e3-962d-bdb229c8eee7.gif)
![tumblr_mio3q9moqv1qdlh1io1_250](https://f.cloud.github.com/assets/170270/2091249/f9624c8c-8e9d-11e3-8bf6-8270ccbc60d2.gif)
![trolls](https://f.cloud.github.com/assets/170270/2091250/f969b846-8e9d-11e3-9f17-a3c42fcfd544.gif)
![tumblr_mirac8cr2r1qdlh1io1_250](https://f.cloud.github.com/assets/170270/2091251/f969f9dc-8e9d-11e3-8634-143f7c6b7435.gif)
![tumblr_mjo5yqbr2e1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091254/f971ea0c-8e9d-11e3-8805-74d060d459f2.gif)
![tumblr_mjqogjio231qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091252/f971fc18-8e9d-11e3-96a0-87a8b7169c5c.gif)
![tumblr_mj9nwoanku1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091253/f971eb56-8e9d-11e3-9f79-e3e144ae7a34.gif)
![tumblr_mjvx1ywg6f1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091255/f976faf6-8e9d-11e3-8612-1134425427e1.gif)
![tumblr_mkstjzivtd1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091257/f97e8078-8e9d-11e3-8444-4c228a829496.gif)
![tumblr_mk77lvyp4t1qdlh1io1_250](https://f.cloud.github.com/assets/170270/2091256/f97e5c92-8e9d-11e3-8f8e-04b0c52c8c68.gif)
![tumblr_ml9za9ecsb1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091258/f9862e54-8e9d-11e3-8e19-2a5c5c56ca18.gif)
![tumblr_mkwooez15j1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091259/f98744f6-8e9d-11e3-9763-188448dcc11e.gif)
![tumblr_mlbp5qhlr81qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091260/f9874514-8e9d-11e3-9315-cb95837d364e.gif)
![tumblr_mlf8zt33uq1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091261/f98c9852-8e9d-11e3-8d8c-61558e09fd3d.gif)
![tumblr_mlq5xqzybs1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091263/f9927f6a-8e9d-11e3-9974-573d3d9866f7.gif)
![tumblr_mlqrgamy9f1qdlh1io1_250](https://f.cloud.github.com/assets/170270/2091262/f992751a-8e9d-11e3-8d6a-2fb629bb4daf.gif)
![tumblr_mm5bjfdbg61qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091264/f99a9c90-8e9d-11e3-9630-4297777b2dfa.gif)
![tumblr_mmk9bcphgf1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091265/f99bb080-8e9d-11e3-8594-87239edac295.gif)
![tumblr_mmi6varome1qdlh1io1_250](https://f.cloud.github.com/assets/170270/2091266/f99c8668-8e9d-11e3-9228-35843df877a4.gif)
![2013-08-05](https://f.cloud.github.com/assets/170270/2091267/f9a251ba-8e9d-11e3-8a46-bec5644e63fc.gif)
![tumblr_mqzn2glr0b1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091268/f9a737f2-8e9d-11e3-825f-5c355987dd6a.gif)
![post-15086-polar-bear-going-in-dry-gif-aolr](https://f.cloud.github.com/assets/170270/2091269/f9a891c4-8e9d-11e3-9091-3d7d56e3f95f.gif)
![tumblr_mndj28lzs21qdlh1io1_250](https://f.cloud.github.com/assets/170270/2091270/f9b041d0-8e9d-11e3-9b1b-94e534164b75.gif)
![tumblr_mocj5pemdh1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091271/f9b0bcbe-8e9d-11e3-81fe-9dadff440b61.gif)
![tumblr_mnmxwo1dyu1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091272/f9b0e50e-8e9d-11e3-8dd0-d4a7eea92392.gif)
![tumblr_mpamnkvlcv1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091273/f9b840a6-8e9d-11e3-945d-0f1a780ed379.gif)
![tumblr_mpncc8jxsq1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091274/f9bb163c-8e9d-11e3-859c-4557a8a0f816.gif)
![tumblr_mpsnnqyswc1qdlh1io1_250](https://f.cloud.github.com/assets/170270/2091275/f9bdb806-8e9d-11e3-8090-8afc279361f2.gif)
![tumblr_mq3srsfoen1qdlh1io1_250](https://f.cloud.github.com/assets/170270/2091276/f9c475e2-8e9d-11e3-9b37-05621a45f541.gif)
![tumblr_mq7wodjuec1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091278/f9c6298c-8e9d-11e3-9970-c6bca623ceb7.gif)
![tumblr_mqirnwrizl1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091277/f9c62450-8e9d-11e3-83f1-a89b570da6d1.gif)
![tumblr_mqj6rwdbqa1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091279/f9cd1314-8e9d-11e3-9d40-1f223173b95f.gif)
![tumblr_mqmk6j8kkz1qdlh1io1_250](https://f.cloud.github.com/assets/170270/2091280/f9cf6bfa-8e9d-11e3-9418-8ed078c5e220.gif)
![tumblr_mqnak1l3cv1qdlh1io1_400](https://f.cloud.github.com/assets/170270/2091281/f9d2a89c-8e9d-11e3-8520-40ab778866f9.gif)
![brave-cat](https://f.cloud.github.com/assets/170270/2091282/f9d9a386-8e9d-11e3-93db-12b33a5e86f9.gif)
![original](https://f.cloud.github.com/assets/170270/2091283/f9db19fa-8e9d-11e3-9458-7d7ba9525e15.gif)
![template-hahahano](https://f.cloud.github.com/assets/170270/2091284/f9db7aa8-8e9d-11e3-9a79-c13acba29784.gif)
![supercorn](https://f.cloud.github.com/assets/170270/2091285/f9e2d8f2-8e9d-11e3-99c3-abf85ae6e606.gif)

**Comment by tgvashworth** [comment]
this i don't i can't why is and oh my but holy yes

**Comment by sindresorhus** [comment]
@addyosmani if you need a jank testcase, feel free to use :p

**Comment by passy** [comment]
hholy what is agreed yes YES YESS

**Comment by btford** [comment]
:+1:

**Comment by fayimora** [comment]
:laughing: :+1:

**Comment by callmehiphop** [comment]
needs more pics

**Comment by stephenplusplus** [comment]
I'm satisfied.
