### ISSUE TITLE
horses, too

### ISSUE THREAD

**Issue by stephenplusplus** [taptapship/sindresorhus#2]
see #1

**Comment by sindresorhus** [comment]
![fat-horse-1](https://cloud.githubusercontent.com/assets/170270/3799859/fb9706f0-1bf1-11e4-8c2f-482e87b0fcb9.jpeg)

![fat-horse1](https://cloud.githubusercontent.com/assets/170270/3799861/0c636168-1bf2-11e4-90d2-4ed5b60d6d6c.jpg)

**Comment by stephenplusplus** [comment]
wow.

**Comment by stephenplusplus** [comment]
Jess just came to visit me "at work" (my backyard) with this on my screen. This is work, honey.

**Comment by sindresorhus** [comment]
Could be worse. She could have caught you doing CoffeeScript :p

**Comment by stephenplusplus** [comment]
OMG noooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
